"""Add member_id field to members table

Revision ID: 03b9b2451bd9
Revises: 0b944542ccd8
Create Date: 2025-12-08 14:34:30.337799+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03b9b2451bd9"
down_revision: Union[str, None] = "0b944542ccd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("advertisements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_advertisements_event_hash_unique"))
        batch_op.create_unique_constraint(
            "uq_advertisements_event_hash", ["event_hash"]
        )

    with op.batch_alter_table("members", schema=None) as batch_op:
        # Add member_id as nullable first to handle existing data
        batch_op.add_column(
            sa.Column("member_id", sa.String(length=100), nullable=True)
        )

    # Generate member_id for existing members based on their name
    # Convert name to lowercase and replace spaces with underscores
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "UPDATE members SET member_id = LOWER(REPLACE(name, ' ', '_')) WHERE member_id IS NULL"
        )
    )

    with op.batch_alter_table("members", schema=None) as batch_op:
        # Now make it non-nullable and add unique index
        batch_op.alter_column("member_id", nullable=False)
        batch_op.drop_index(batch_op.f("ix_members_name"))
        batch_op.create_index(
            batch_op.f("ix_members_member_id"), ["member_id"], unique=True
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_event_hash_unique"))
        batch_op.create_unique_constraint("uq_messages_event_hash", ["event_hash"])

    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nodes_public_key"))
        batch_op.create_index(
            batch_op.f("ix_nodes_public_key"), ["public_key"], unique=True
        )

    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telemetry_event_hash_unique"))
        batch_op.create_unique_constraint("uq_telemetry_event_hash", ["event_hash"])

    with op.batch_alter_table("trace_paths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trace_paths_event_hash_unique"))
        batch_op.create_unique_constraint("uq_trace_paths_event_hash", ["event_hash"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trace_paths", schema=None) as batch_op:
        batch_op.drop_constraint("uq_trace_paths_event_hash", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_trace_paths_event_hash_unique"), ["event_hash"], unique=1
        )

    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.drop_constraint("uq_telemetry_event_hash", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_telemetry_event_hash_unique"), ["event_hash"], unique=1
        )

    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nodes_public_key"))
        batch_op.create_index(
            batch_op.f("ix_nodes_public_key"), ["public_key"], unique=False
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint("uq_messages_event_hash", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_messages_event_hash_unique"), ["event_hash"], unique=1
        )

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_member_id"))
        batch_op.create_index(batch_op.f("ix_members_name"), ["name"], unique=False)
        batch_op.drop_column("member_id")

    with op.batch_alter_table("advertisements", schema=None) as batch_op:
        batch_op.drop_constraint("uq_advertisements_event_hash", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_advertisements_event_hash_unique"), ["event_hash"], unique=1
        )

    # ### end Alembic commands ###
